export const BRANCH_LIST = [
  { id: 0, branch: '전체' },
  { id: 1, branch: '평택 쇼룸 코오롱모터스' },
  { id: 2, branch: '분당전시장 코오롱모터스' },
  { id: 3, branch: '위례전시장 코오롱모터스' },
  { id: 4, branch: '삼성전시장 코오롱모터스' },
  { id: 5, branch: '강남전시장 코오롱모터스' },
  { id: 6, branch: '용산 쇼룸 코오롱모터스' },
  { id: 7, branch: '부천전시장 코오롱모터스' },
  { id: 8, branch: 'BPS 부천전시장 코오롱모터스' },
  { id: 9, branch: '대전 아트앤사이언스 전시장 코오롱모터스' },
  { id: 10, branch: '대전전시장 코오롱모터스' },
  { id: 11, branch: '의정부전시장 코오롱모터스' },
  { id: 12, branch: '구미전시장 코오롱모터스' },
  { id: 13, branch: '대구전시장 코오롱모터스' },
  { id: 14, branch: '광주전시장 코오롱모터스' },
  { id: 15, branch: '순천전시장 코오롱모터스' },
  { id: 16, branch: '김해전시장 코오롱모터스' },
  { id: 17, branch: '부산남구전시장 코오롱모터스' },
];
